service: wow-project

provider:
  name: aws
  runtime: nodejs12.x
  profile: paulo
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::${self:custom.s3Bucket}
        - arn:aws:s3:::${self:custom.s3Bucket}/*
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - "*"

plugins:
  - serverless-s3-remover

custom:
  stage: ${opt:stage, dev}
  s3Bucket: data-acquisition-${self:custom.stage}
  remover:
    buckets:
      - ${self:custom.s3Bucket}
  enabler:
    prod: true
    dev: false
    default: false

# resources:
#   Resources:
#     DataLake:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${self:custom.s3Bucket}

functions:
    acquisition:
        handler: build/index.acquisition
        timeout: 300
        memorySize: 192
        environment:
          stage: ${self:custom.stage}
        events:
          - schedule:
              rate: cron(0 0 * * ? *)
              enabled: ${self:custom.enabler.${self:custom.stage}, self:custom.enabler.default}
              input:
                realmName: Proudmoore

    ignition:
        handler: build/index.ignition
        timeout: 900
        memorySize: 192
        environment:
          stage: ${self:custom.stage}
        events:
          - schedule:
              rate: cron(0 0 * * ? *)
              enabled: false

    anomalyDetection:
      handler: build/index.anomalyDetection
      timeout: 300
      memorySize: 192
      environment:
        stage: ${self:custom.stage}
      events:
        - s3:
            bucket: ${self:custom.s3Bucket}
            event: s3:ObjectCreated:*